#!/bin/sh

. /etc/profile

start()
{
    start-stop-daemon -S -q -b -m -p /var/run/egt_dash.pid --exec egt_dash
}

stop()
{
    start-stop-daemon -K -q -p /var/run/egt_dash.pid
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    *)
	;;
esac
